### ISSUE TITLE
DataError at /google_sso/callback/: value too long for type character varying(255)

### ISSUE THREAD

**Issue by savionak** [chrismaille/django-google-sso#6]
Hello again.
Got a different error when I was trying to login: `DataError at /google_sso/callback/: value too long for type character varying(255)`. 
It seems that my profile image URL is too long (it's 995 characters) and didn't fit in `picture_url` field.
Could you please increase the limit?

**Comment by chrismaille** [comment]
Hi. Please, can you reproduce here the traceback, so I can double check here the error?

Thanks!

**Comment by savionak** [comment]
Sure:
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

The above exception (value too long for type character varying(255)
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_google_sso/views.py", line 81, in callback
    user = user_helper.get_or_create_user()
  File "/usr/local/lib/python3.8/site-packages/django_google_sso/main.py", line 110, in get_or_create_user
    google_user.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 831, in save
    self.save_base(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 882, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 995, in _save_table
    updated = self._do_update(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1059, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1215, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1819, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: DataError at /google_sso/callback/
Exception Value: value too long for type character varying(255)

```
